pipeline {
    agent any
     stages {
    stage('Checkout') {
      steps {
        sh 'echo passed'
        //git branch: 'main', url: 'https://github.com/test0666/test0666_repo.git'
      }
    }   
    
    stages {
        stage('Install Maven') {
            steps {
                sh '''
                sudo apt update
                sudo apt install -y maven
                mvn -version
                '''
            }
        }
    }
 }      
}
