pipeline {
    agent any

    stages {
        stage('Install Maven') {
            steps {
                sh '''
                sudo apt update
                sudo apt install -y maven
                mvn -version
                '''
            }
        }
    }
}
